/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ContratoJpaController;
import Controlador.CuotaJpaController;
import Controlador.EmpresaJpaController;
import Controlador.PagoJpaController;
import Modelo.Contrato;
import Modelo.Cuota;
import Modelo.Empresa;
import Modelo.EstadoContrato;
import Modelo.EstadoPago;
import Modelo.Pago;
import Modelo.TipoPago;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivans
 */
public class agregarContrato extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    private Empresa empresa;
    private EmpresaJpaController controllerEmp;
    private Contrato contrato;
    private ContratoJpaController controllerCon;
    private Pago pago;
    private TipoPago tipoPago;
    private PagoJpaController controllerPago;
    private EstadoContrato estadoContrato;
    private EstadoPago estadoPago;
    private Cuota cuota;
    private CuotaJpaController controllerCuota;
    DefaultTableModel modelo;
    public agregarContrato() {
        initComponents();
        controllerEmp = new EmpresaJpaController();
        controllerCon = new ContratoJpaController();
        controllerPago = new PagoJpaController();
        estadoPago = new EstadoPago(BigDecimal.valueOf(2), "No pagado");
        estadoContrato = new EstadoContrato(BigDecimal.valueOf(1), "En curso");       
        controllerCuota = new CuotaJpaController();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpresa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dateInicio = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateFechaPago = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtCantCuotas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbPago = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(15, 14, 140));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 170, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_no_entry_32px_1.png"))); // NOI18N
        sidepane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("No Mas Accidentes");
        sidepane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, 20));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 670));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setName(""); // NOI18N

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Buscador por razon social:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btn.setText("Limpiar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btn)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btn))
                .addGap(23, 23, 23))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 820, 80));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, -1, 30));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione Empresa:");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        tblEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEmpresa);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 800, 160));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha Inicio Contrato:");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, 20));
        bg.add(dateInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 150, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Monto Total:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));
        bg.add(txtMontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 120, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha de Pago:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));
        bg.add(dateFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 150, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cantidad Cuotas:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, -1));
        bg.add(txtCantCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, 100, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tipo Pago:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, -1));

        cbPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Credito", "Efectivo", "Debito" }));
        bg.add(cbPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, 120, -1));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        bg.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 110, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        bg.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        dispose();
    }//GEN-LAST:event_jLabel13MousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int coordenadaX = evt.getXOnScreen();
        int coordenadaY = evt.getYOnScreen();
        this.setLocation(coordenadaX - mousepX, coordenadaY - mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int fila = tblEmpresa.getSelectedRow();
        if (fila != -1) {
            Object codigo = tblEmpresa.getValueAt(fila, 0);
            String cod = String.valueOf(codigo);
            int idTipoPago = cbPago.getSelectedIndex();
            String desPago = cbPago.getSelectedItem().toString();
            tipoPago = new TipoPago(BigDecimal.valueOf(idTipoPago), desPago);
            int codigoEmpresa = Integer.parseInt(cod);
            int contador = 0;
            boolean valor = false;
            do{
                contador++;
                valor = controllerCon.buscarCodigo(BigDecimal.valueOf(contador));
            }while(valor == true);
            try{
                empresa = controllerEmp.findEmpresa(BigDecimal.valueOf(codigoEmpresa));
                empresa.getIdEmpresa();
                empresa.getNombre();
                empresa.getRazonSocial();
                empresa.getDireccion();
                empresa.getTelefono();
                empresa.getFechaCreado();
                empresa.getFechaModificado();                
                //aumentar 12 meses el fin del contrato
                if(validarFechas()){
                Date d = dateInicio.getDate();
                Calendar c1 = Calendar.getInstance();
                c1.setTime(d);
                c1.add(Calendar.MONTH,12);
                Date fin = c1.getTime();                
                contrato = new Contrato();
                contrato.setIdContrato(BigDecimal.valueOf(contador));
                contrato.setFechaInicio(dateInicio.getDate());
                contrato.setFechaTermino(fin);
                contrato.setEmpresaIdEmpresa(empresa);
                contrato.setEstadoContratoIdEstCon(estadoContrato);
                controllerCon.create(contrato);
                //creacion de cantidad de cuotas
                String cuotas = txtCantCuotas.getText();
                int cantCuotas = Integer.parseInt(cuotas);
                String monto = txtMontoTotal.getText();
                int montoTotal = Integer.parseInt(monto);
                int montoCuotas = montoTotal/cantCuotas;
                Date fechaPago = dateFechaPago.getDate();
                Calendar c = Calendar.getInstance();
                Calendar vencimiento = Calendar.getInstance();
                c.setTime(fechaPago);
                vencimiento.setTime(fechaPago);
                for (int i = 1; i <= cantCuotas; i++) {
                    boolean v = false;
                    int cont=0;
                    do {                        
                        cont++;
                        v = controllerCuota.buscarCodigo(BigDecimal.valueOf(cont));
                    } while (v == true);
                    
                    vencimiento.add(Calendar.DATE, 10);
                    cuota = new Cuota();
                    cuota.setIdCuota(BigDecimal.valueOf(cont));
                    cuota.setMonto(BigInteger.valueOf(montoCuotas));                   
                    cuota.setFechaPago(c.getTime());
                    cuota.setFechaVencimiento(vencimiento.getTime());                                           
                    cuota.setMonto(BigInteger.valueOf(montoCuotas));
                    cuota.setContratoIdContrato(contrato);
                    controllerCuota.create(cuota);
                    pago = new Pago();
                    pago.setIdPago(BigDecimal.valueOf(cont));
                    pago.setFechaPago(c.getTime());
                    pago.setCuotaIdCuota(cuota);
                    pago.setEstadoPagoIdEstadoPago(estadoPago);
                    pago.setTipoPagoIdTipoPago(tipoPago);
                    controllerPago.create(pago);
                    c.add(Calendar.MONTH, 1);
                    }
                }
                JOptionPane.showMessageDialog(this, "Contrato empresa "+ empresa.getNombre()+" agregado con exito", "Validación", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Validación", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No dejar valores en blanco", "Validación", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarTabla(){
        cargarColumna();
        for (Empresa e : controllerEmp.findEmpresaEntities()) {
            Date fechaCreado = e.getFechaCreado();
            Date fechaModificado = e.getFechaModificado();
            SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
            String fechaText = form.format(fechaCreado);
            String fecha = form.format(fechaModificado);
            modelo.addRow(new Object[]{e.getIdEmpresa(), e.getNombre(), e.getRazonSocial(), e.getDireccion(),e.getTelefono(),fechaText,fecha});
        }
    }
    private void cargarColumna(){
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Razon Social");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("Fecha Creado");
        modelo.addColumn("Fecha Modificado");
        tblEmpresa.setModel(modelo);
    }
    private void limpiar(){
        dateInicio.setDate(null);
        dateFechaPago.setDate(null);
        txtCantCuotas.setText("");
        txtMontoTotal.setText("");
        cbPago.setSelectedItem("Seleccione");
    }
    
    private boolean validarFechas(){
        boolean valor = false; 
        Date fecha1 = dateInicio.getDate();
         Date fecha2 = dateFechaPago.getDate();
        
        if(fecha1.before(fecha2) || fecha1.equals(fecha2)){
          valor = true;
          JOptionPane.showMessageDialog(this, "La fecha es válida", "Validación", JOptionPane.INFORMATION_MESSAGE);                
        }else{
            valor = false;
             JOptionPane.showMessageDialog(this, "La Fecha de Pago no puede ser anterior a la de Contrato", "Validación", JOptionPane.INFORMATION_MESSAGE);
        }
     return valor;   
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbPago;
    private com.toedter.calendar.JDateChooser dateFechaPago;
    private com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel sidepane;
    private javax.swing.JTable tblEmpresa;
    private javax.swing.JTextField txtCantCuotas;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
