/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.math.BigDecimal;
import javax.swing.JPanel;

/**
 *
 * @author ivans
 */
public class inicioProfe extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    login l = new login();
    BigDecimal int1 = l.codigo;
    public static BigDecimal cod;
    public inicioProfe() {
        initComponents();
        this.setLocationRelativeTo(null);        
        lblProfesional.setText(l.nom);
        addChecklist.hide();
        lblAprobarChk.hide();
        addChecklist.hide();
        lblAprobarChk.hide();
        lstChecklist.hide();
        lblAddChecklist1.hide();
        lblAReportCapac.hide();
        lblReportChk.hide();
        lblReportVisitas.hide();
        reportCapacitaciones.hide();
        reportChecklist1.hide();
        reportVisitas.hide();
        setColor(panelInicio);
        resetColor(panelChecklist);
        resetColor(panelReporte);
        resetColor(panelVisita);
        resetColor(panelCapacitacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        panelVisita = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelReporte = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelChecklist = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelCapacitacion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        addChecklist = new javax.swing.JLabel();
        lblAprobarChk = new javax.swing.JLabel();
        lstChecklist = new javax.swing.JLabel();
        lblAddChecklist1 = new javax.swing.JLabel();
        reportCapacitaciones = new javax.swing.JLabel();
        lblAReportCapac = new javax.swing.JLabel();
        reportChecklist1 = new javax.swing.JLabel();
        lblReportChk = new javax.swing.JLabel();
        reportVisitas = new javax.swing.JLabel();
        lblReportVisitas = new javax.swing.JLabel();
        addVisita = new javax.swing.JLabel();
        lblAddVisita = new javax.swing.JLabel();
        modCapacitaciones = new javax.swing.JLabel();
        lblModificarCapac = new javax.swing.JLabel();
        lstVisitas = new javax.swing.JLabel();
        lblReportVisitas1 = new javax.swing.JLabel();
        lblListarCapac = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblProfesional = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(15, 14, 140));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVisita.setBackground(new java.awt.Color(47, 46, 157));
        panelVisita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelVisita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelVisitaMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_business_26px.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Visitas Programadas");

        javax.swing.GroupLayout panelVisitaLayout = new javax.swing.GroupLayout(panelVisita);
        panelVisita.setLayout(panelVisitaLayout);
        panelVisitaLayout.setHorizontalGroup(
            panelVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVisitaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelVisitaLayout.setVerticalGroup(
            panelVisitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVisitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 50));

        panelReporte.setBackground(new java.awt.Color(47, 46, 157));
        panelReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelReporteMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_graph_report_32px_1.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Generar Reporte");

        javax.swing.GroupLayout panelReporteLayout = new javax.swing.GroupLayout(panelReporte);
        panelReporte.setLayout(panelReporteLayout);
        panelReporteLayout.setHorizontalGroup(
            panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelReporteLayout.setVerticalGroup(
            panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 50));

        panelChecklist.setBackground(new java.awt.Color(47, 46, 157));
        panelChecklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelChecklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelChecklistMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_to_do_26px.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Checklist");

        javax.swing.GroupLayout panelChecklistLayout = new javax.swing.GroupLayout(panelChecklist);
        panelChecklist.setLayout(panelChecklistLayout);
        panelChecklistLayout.setHorizontalGroup(
            panelChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChecklistLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelChecklistLayout.setVerticalGroup(
            panelChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChecklistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelChecklist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 50));

        panelCapacitacion.setBackground(new java.awt.Color(47, 46, 157));
        panelCapacitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCapacitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCapacitacionMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_training_24px.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Capacitaciones");

        javax.swing.GroupLayout panelCapacitacionLayout = new javax.swing.GroupLayout(panelCapacitacion);
        panelCapacitacion.setLayout(panelCapacitacionLayout);
        panelCapacitacionLayout.setHorizontalGroup(
            panelCapacitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCapacitacionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelCapacitacionLayout.setVerticalGroup(
            panelCapacitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCapacitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 50));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 170, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_no_entry_32px_1.png"))); // NOI18N
        sidepane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("No Mas Accidentes");
        sidepane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, 20));

        panelInicio.setBackground(new java.awt.Color(47, 46, 157));
        panelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelInicioMousePressed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_home_32px.png"))); // NOI18N

        Inicio.setBackground(new java.awt.Color(255, 255, 255));
        Inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(204, 204, 204));
        Inicio.setText("Inicio");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidepane.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 820, 50));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, -1, 30));

        addChecklist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addChecklist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/54e5ce28-c16f-4e2a-8682-4424e257fbbf.png"))); // NOI18N
        addChecklist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addChecklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addChecklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addChecklistMouseClicked(evt);
            }
        });
        bg.add(addChecklist, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 160, 160));

        lblAprobarChk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAprobarChk.setForeground(new java.awt.Color(0, 0, 0));
        lblAprobarChk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAprobarChk.setText("Aprobar Formulario");
        bg.add(lblAprobarChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 160, 20));

        lstChecklist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lstChecklist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/54e5ce28-c16f-4e2a-8682-4424e257fbbf.png"))); // NOI18N
        lstChecklist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstChecklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lstChecklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstChecklistMouseClicked(evt);
            }
        });
        bg.add(lstChecklist, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 160, 160));

        lblAddChecklist1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddChecklist1.setForeground(new java.awt.Color(0, 0, 0));
        lblAddChecklist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddChecklist1.setText("Generar Formulario");
        bg.add(lblAddChecklist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 160, 20));

        reportCapacitaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportCapacitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/52d1617b-0f47-4a12-93a7-d90fef62681d.png"))); // NOI18N
        reportCapacitaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportCapacitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportCapacitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportCapacitacionesMouseClicked(evt);
            }
        });
        bg.add(reportCapacitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 160, 160));

        lblAReportCapac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAReportCapac.setForeground(new java.awt.Color(0, 0, 0));
        lblAReportCapac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAReportCapac.setText("Reporte Capacitaciones");
        bg.add(lblAReportCapac, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 170, 20));

        reportChecklist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportChecklist1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/52d1617b-0f47-4a12-93a7-d90fef62681d.png"))); // NOI18N
        reportChecklist1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportChecklist1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportChecklist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportChecklist1MouseClicked(evt);
            }
        });
        bg.add(reportChecklist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 160, 160));

        lblReportChk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReportChk.setForeground(new java.awt.Color(0, 0, 0));
        lblReportChk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportChk.setText("Reporte Checklist");
        bg.add(lblReportChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 160, 20));

        reportVisitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportVisitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/52d1617b-0f47-4a12-93a7-d90fef62681d.png"))); // NOI18N
        reportVisitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportVisitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportVisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportVisitasMouseClicked(evt);
            }
        });
        bg.add(reportVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 160, 160));

        lblReportVisitas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReportVisitas.setForeground(new java.awt.Color(0, 0, 0));
        lblReportVisitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportVisitas.setText("Reporte Visitas");
        bg.add(lblReportVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 160, 20));

        addVisita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addVisita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/54e5ce28-c16f-4e2a-8682-4424e257fbbf.png"))); // NOI18N
        addVisita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addVisita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addVisita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addVisitaMouseClicked(evt);
            }
        });
        bg.add(addVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 160, 160));

        lblAddVisita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddVisita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddVisita.setText("Agregar Capacitacion");
        bg.add(lblAddVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 160, 20));

        modCapacitaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modCapacitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/54e5ce28-c16f-4e2a-8682-4424e257fbbf.png"))); // NOI18N
        modCapacitaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        modCapacitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modCapacitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modCapacitacionesMouseClicked(evt);
            }
        });
        bg.add(modCapacitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 160, 160));

        lblModificarCapac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModificarCapac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarCapac.setText("Aprobar Formulario");
        bg.add(lblModificarCapac, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 160, 20));

        lstVisitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lstVisitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/54e5ce28-c16f-4e2a-8682-4424e257fbbf.png"))); // NOI18N
        lstVisitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstVisitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lstVisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstVisitasMouseClicked(evt);
            }
        });
        bg.add(lstVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 160, 160));

        lblReportVisitas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReportVisitas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportVisitas1.setText("Reporte Visitas");
        bg.add(lblReportVisitas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 160, 20));

        lblListarCapac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListarCapac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListarCapac.setText("Listar Capacitaciones");
        bg.add(lblListarCapac, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 160, 20));

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Bienvenido: ");
        bg.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 54));

        lblProfesional.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblProfesional.setForeground(new java.awt.Color(0, 0, 0));
        lblProfesional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(lblProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 290, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelVisitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVisitaMousePressed
        addChecklist.hide();
        lblAprobarChk.hide();
        lstChecklist.hide();
        lblAddChecklist1.hide();
        lblAReportCapac.hide();
        lblReportChk.hide();
        lblReportVisitas.hide();
        reportCapacitaciones.hide();
        reportChecklist1.hide();
        reportVisitas.hide();
        setColor(panelVisita);
        resetColor(panelChecklist);
        resetColor(panelReporte);
        resetColor(panelCapacitacion);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelVisitaMousePressed

    private void panelReporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelReporteMousePressed
        addChecklist.hide();
        lblAprobarChk.hide();
        lstChecklist.hide();
        lblAddChecklist1.hide();
        lblAReportCapac.show();
        lblReportChk.show();
        lblReportVisitas.show();
        reportCapacitaciones.show();
        reportChecklist1.show();
        reportVisitas.show();
        setColor(panelReporte);
        resetColor(panelChecklist);
        resetColor(panelVisita);
        resetColor(panelCapacitacion);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelReporteMousePressed

    private void panelChecklistMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelChecklistMousePressed
        addChecklist.show();
        lblAprobarChk.show();
        lstChecklist.show();
        addChecklist.show();
        lblAprobarChk.show();
        lstChecklist.show();
        lblAddChecklist1.show();
        lblAReportCapac.hide();
        lblReportChk.hide();
        lblReportVisitas.hide();
        reportCapacitaciones.hide();
        reportChecklist1.hide();
        reportVisitas.hide();
        setColor(panelChecklist);
        resetColor(panelReporte);
        resetColor(panelVisita);
        resetColor(panelCapacitacion);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelChecklistMousePressed

    private void panelCapacitacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCapacitacionMousePressed
        addChecklist.hide();
        lblAprobarChk.hide();
        addChecklist.hide();
        lblAprobarChk.hide();
        lstChecklist.hide();
        lblAddChecklist1.hide();
        lblAReportCapac.hide();
        lblReportChk.hide();
        lblReportVisitas.hide();
        reportCapacitaciones.hide();
        reportChecklist1.hide();
        reportVisitas.hide();
        setColor(panelCapacitacion);
        resetColor(panelChecklist);
        resetColor(panelReporte);
        resetColor(panelVisita);
        resetColor(panelInicio);
    }//GEN-LAST:event_panelCapacitacionMousePressed

    private void panelInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInicioMousePressed
        addChecklist.hide();
        lblAprobarChk.hide();
        addChecklist.hide();
        lblAprobarChk.hide();
        lstChecklist.hide();
        lblAddChecklist1.hide();
        lblAReportCapac.hide();
        lblReportChk.hide();
        lblReportVisitas.hide();
        reportCapacitaciones.hide();
        reportChecklist1.hide();
        reportVisitas.hide();
        setColor(panelInicio);
        resetColor(panelChecklist);
        resetColor(panelReporte);
        resetColor(panelVisita);
        resetColor(panelCapacitacion);
    }//GEN-LAST:event_panelInicioMousePressed

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(96, 95, 249));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(47, 46, 157));
    }
    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        dispose();
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_jLabel13MousePressed

    private void addChecklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addChecklistMouseClicked
        cod = int1;
        
    }//GEN-LAST:event_addChecklistMouseClicked

    private void lstChecklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstChecklistMouseClicked
        cod = int1;
        
    }//GEN-LAST:event_lstChecklistMouseClicked

    private void reportCapacitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportCapacitacionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reportCapacitacionesMouseClicked

    private void reportChecklist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportChecklist1MouseClicked
        cod = int1;
        
    }//GEN-LAST:event_reportChecklist1MouseClicked

    private void reportVisitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportVisitasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reportVisitasMouseClicked

    private void addVisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addVisitaMouseClicked
        cod = int1;
        
    }//GEN-LAST:event_addVisitaMouseClicked

    private void modCapacitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modCapacitacionesMouseClicked
        
    }//GEN-LAST:event_modCapacitacionesMouseClicked

    private void lstVisitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstVisitasMouseClicked
        cod = int1;
        
    }//GEN-LAST:event_lstVisitasMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int coordenadaX = evt.getXOnScreen();
        int coordenadaY = evt.getYOnScreen();
        this.setLocation(coordenadaX - mousepX, coordenadaY - mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(inicioProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(inicioProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(inicioProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(inicioProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new inicioProfe().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel addChecklist;
    private javax.swing.JLabel addVisita;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAReportCapac;
    private javax.swing.JLabel lblAddChecklist1;
    private javax.swing.JLabel lblAddVisita;
    private javax.swing.JLabel lblAprobarChk;
    private javax.swing.JLabel lblListarCapac;
    private javax.swing.JLabel lblModificarCapac;
    private javax.swing.JLabel lblProfesional;
    private javax.swing.JLabel lblReportChk;
    private javax.swing.JLabel lblReportVisitas;
    private javax.swing.JLabel lblReportVisitas1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lstChecklist;
    private javax.swing.JLabel lstVisitas;
    private javax.swing.JLabel modCapacitaciones;
    private javax.swing.JPanel panelCapacitacion;
    private javax.swing.JPanel panelChecklist;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelReporte;
    private javax.swing.JPanel panelVisita;
    private javax.swing.JLabel reportCapacitaciones;
    private javax.swing.JLabel reportChecklist1;
    private javax.swing.JLabel reportVisitas;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
